### PR TITLE
Updated change log

### PR DESCRIPTION
**Pull request by Nyholm**
Please review master. I will tag 1.5.0 after this PR is merged.

### CODE REVIEW

**Comment by fbourigault** [comment]
What about https://github.com/php-http/HttplugBundle/pull/142 for HttpAsyncClient?

**Comment by fbourigault** [comment]
We have to remove https://github.com/php-http/HttplugBundle/blob/master/DependencyInjection/HttplugExtension.php#L437-L438 because it's no longer required since #135.

**Comment by Nyholm** [comment]
There is already mention of #142.

> Support for autowring in Symfony 3.3

**Comment by Nyholm** [comment]
I just created some PRs for 1.5.0. Just smaller things. Im fine with releasing 1.5.0 after they are accepted.

**Comment by Nyholm** [comment]
@dbu Are you fine with releasing 1.5.0?

**Comment by dbu** [comment]
sorry, at a workshop yesterday and today. if you are confident for the
release i trust you guys. but if you want me to have a look i can take a
bit of time tomorrow.

**Comment by Nyholm** [comment]
Im confident. But there is no rush. I will release this on Monday if not before.

**Comment by fbourigault** [comment]
I'm confident too :)

**Comment by Nyholm** [comment]
Thank you.
Yeah #166 is a blocker

**Pull request merged**
