### PR TITLE
Add plugin container parameters

### PR DESCRIPTION
**Pull request by sagikazarmark**

### CODE REVIEW

**Comment by xabbuh** [comment]
Is there a special use case you need the service class names to be controlled through container parameters?

**Comment by sagikazarmark** [comment]
It would have been easier when we changed the namespace. It's quite common
that you have to create your own plugin services. I thought it might be
better to have a parameter instead of class names.

Am I wrong?

Christian Flothmann <notifications@github.com> ezt írta (2016. május 29.,
vasárnap):

**Comment by dbu** [comment]
symfony started deprecating this pattern and stopped doing it in symfony 3. i am -1 introducing this here. we hopefully won't change class names again. and we open the door to let people change those paramters to instantiate other plugin classes which is a real antipattern.

**Comment by sagikazarmark** [comment]
Okay, thanks for clarification (again) :smile:

**Pull request closed without merging**
