### PR TITLE
Add gray icon under 2.8

### PR DESCRIPTION
**Pull request by sagikazarmark**

### CODE REVIEW

**Comment by sagikazarmark** [comment]
@Nyholm can you please test this if you have some time?

**Comment by Nyholm** [comment]
Of course. I'll do it within the hour.

**Comment by sagikazarmark** [comment]
Feel free to merge it if it looks good. Don't care about failing builds, fix is in another PR.

**Comment by Nyholm** [comment]
It was a minor issue, the default height should be 28 in SF2.7. That is now fixed,

**Pull request merged**
