### PR TITLE
Release 1.17

### PR DESCRIPTION
**Pull request by Nyholm**
I've confirmed that the change log is up to date. 

I'm happy to release a new version =)

### CODE REVIEW

**Comment by Nyholm** [comment]
Maybe we should wait for #362 first.

**Comment by dbu** [comment]
i wait for the cache plugin release with this one.

**Comment by Nyholm** [comment]
I've moved test-ci to PHP7.3 because it timed out on PHP7.4.

**Comment by Nyholm** [comment]
Thank you for merging

**Pull request merged**
