### PR TITLE
Enhancement: Normalize composer.json

### PR DESCRIPTION
**Pull request by localheinz**
| Q               | A
| --------------- | ---
| Bug fix?        | no
| New feature?    | no
| BC breaks?      | no
| Deprecations?   | no
| Related tickets | n/a
| Documentation   | n/a
| License         | MIT

#### What's in this PR?

This PR

* [x] normalizes `composer.json`

💁‍♂️ I ran

```
$ composer global require localheinz/composer-normalize
```

followed by

```
$ composer normalize
```

#### Why?

A follow-up to #39.

Also see https://github.com/localheinz/composer-normalize.
#### Example Usage

n/a

#### Checklist

n/a

#### To Do

n/a

### CODE REVIEW

**Comment by localheinz** [comment]
Build failure is fixed in #336.

**Comment by dbu** [comment]
can you please rebase this on master?

**Comment by localheinz** [comment]
@dbu 

Done!

**Comment by dbu** [comment]
thanks!

**Comment by localheinz** [comment]
Thank you, @dbu!

**Pull request merged**
