### PR TITLE
Added tests for Guzzle6, Curl, React and Socket factories

### PR DESCRIPTION
**Pull request by Nyholm**
This PR is a blocker for the tests to pass:  https://github.com/php-http/react-adapter/pull/10

### CODE REVIEW

**Comment by dbu** [comment]
:+1: 

do you also define the curl and react factories as services? if i understand the doc correctly, we only have guzzle 5 and 6 for now.

**Comment by Nyholm** [comment]
Yes I do. 

Also, I think you missed one of my changes in the doc PR: https://github.com/php-http/documentation/pull/93/files#diff-33b9b1161d0ce83931e73c48bf9e6900R106

**Comment by dbu** [comment]
ah, very cool!

**Comment by sagikazarmark** [comment]
:+1:

**Pull request merged**
