### PR TITLE
Added an sf4 example for enabling the bundle

### PR DESCRIPTION
**Pull request by gmponos**
| Q               | A
| --------------- | ---
| Bug fix?        | no
| New feature?    | no
| BC breaks?      | no
| Deprecations?   | no
| Documentation   | Yes
| License         | MIT

#### What's in this PR?

Update the README file on how to register/enable the bundle.

TBH it might be preferable to point to an external resource.

### CODE REVIEW

**Comment by dbu** [comment]
thanks. this is better than explaining the symfony 3 way.

we have https://php-http.readthedocs.io/en/latest/integrations/symfony-bundle.html which seems like the right external source. can you change the readme to only explain the flex way, and link to the documentation for the installation without flex? and do this PR against the documentation to explain the symfony 4/5 way of things?

**Comment by dbu** [comment]
see #380 and https://github.com/php-http/documentation/pull/275

**Comment by dbu** [comment]
thanks for bringing this up @gmponos

**Comment by gmponos** [comment]
arggg.. my mind always forgets things like documentations and stuff.. totally forgot to update this PR.

Anyway glad it helped in anyway...

**Comment by dbu** [comment]
no worries, was quick to wrap it up, thanks for having realized it in the first place!

**Pull request closed without merging**
