### PR TITLE
fix dependencies

### PR DESCRIPTION
**Pull request by dbu**
(i hope)

### CODE REVIEW

**Comment by dbu** [comment]
i have the impression that `^0.3.1` is not as flexible as we probably think. seems that does not allow 0.4.0. maybe that is the semantics with 0.x versions?

**Comment by sagikazarmark** [comment]
Yes.

^0.3 is translated to >=0.3,<0.4 (BUT: ^1.1 = >=1.1,<2.0)
~0.3 is translated to >=0.3,<1.0

**Comment by sagikazarmark** [comment]
Reasoning: BC break is allowed between MJZ versions, so you might not want to update to a new minor version.

**Comment by dbu** [comment]
makes sense.

okay, and now it installs again, but one of the tests fails. will investigate and update this PR.

**Pull request merged**
