### PR TITLE
Updated toolbar logo

### LINKED ISSUE #23: New toolbar icon
The icon that is used in the web-toolbar is the exact same as the Ajax toolbar. We should create our own `icon.svg`. 

Maybe with straight arrows going back and froth instead of bent? Or maybe a white version of our logo?

### PR DESCRIPTION
**Pull request by Nyholm**
This will fix #23 

screen shot 2016-01-11 at 09 57 22
screen shot 2016-01-11 at 09 57 28

### CODE REVIEW

**Comment by sagikazarmark** [comment]
I would just call it httplug.svg in this context.

:+1:

**Comment by sagikazarmark** [comment]
Thanks @Nyholm

**Comment by Nyholm** [comment]
Thank you for creating the logo.

**Comment by dbu** [comment]
awesome, thanks!

**Pull request merged**
