### PR TITLE
URLify header value links

### PR DESCRIPTION
**Pull request by ostrolucky**
Reference: https://github.com/php-http/HttplugBundle/pull/355#issuecomment-555062832

### CODE REVIEW

**Comment by ostrolucky** [comment]
Damit actually I forgot to test this with https and mistakenly used ?s instead of s?

**Comment by dbu** [comment]
oops, also overlooked that one. at least it works if you do httpXs :grin: 

i guess adding automated tests for this is quite complicated, not sure its worth it.

**Comment by dbu** [comment]
are you going to do a follow-up pull request to correct it?

**Comment by ostrolucky** [comment]
Yes, in couple days perhaps

**Comment by dbu** [comment]
i made #368 - that is all we need, or am i missing something?

**Pull request merged**
