### PR TITLE
Added stopwatch plugin

### LINKED ISSUE #92: Integrate with Symfony Debug Timeline
| Q            | A
| ------------ | ---
| Bug?         | no
| New Feature? | yes
| Version      | n/a

Looking at @csarrazi's [Guzzle Bundle](https://github.com/csarrazi/CsaGuzzleBundle) they have a really nice integration with the Symfony Debug timeline. That is something we should support as well.

### PR DESCRIPTION
**Pull request by Nyholm**
| Q               | A
| --------------- | ---
| Bug fix?        | no
| New feature?    | yes
| BC breaks?      | yes
| Deprecations?   | no
| Related tickets | fixes #92
| Documentation   | 
| License         | MIT

#### What's in this PR?

With this PR we integrate with the WebProfiler timeline

screen shot 2016-07-25 at 03 01 39

### CODE REVIEW

**Comment by sagikazarmark** [comment]
What happens if a custom stopwatch (either the httplug service or a completely custom one) is added to the plugin stack?

**Comment by Nyholm** [comment]
If someone uses the default stopwatchPlugin we are doing the same calls to the stopwatch component twice. That means that our measured times would be twice as large. 

If someone uses the stopwatchPlugin with a custom stopwatch, then nothing special will happen.

**Comment by sagikazarmark** [comment]
Okay, so probably we should add a check to see if the stopwatch plugin is already added? And then do what? Leave it as is, or remove that one and add our own to the beginning of the stack?

**Comment by joelwurtz** [comment]
Or just a check in the StopwatchPlugin to do nothing if the event is already started ? (there is a `isStarted` method in stopwatch)

**Comment by Nyholm** [comment]
Our (the automatic one) stopwatch plugin is the first to execute though.

**Comment by Nyholm** [comment]
But why would someone add their own stopwatch plugin? I we could figure out that use case it may be easier to know the appropriate action to take.

**Comment by Nyholm** [comment]
I answering my own question now. The reason you may want to add the stopwatch plugin may be because you want to change the order. Say you have one slow plugin in the beginning that you want to exclude for the stopwatch. 

I believe we should check if the stopwatch is added and only prepend the plugin list if the stopwatch is missing. What do you think?

**Comment by sagikazarmark** [comment]
Like that, but maybe we should only check our stopwatch plugin service. If someone creates a custom stopwatch plugin service, it might not use the same stopwatch instance. WDYT?

**Comment by Nyholm** [comment]
Agreed.

**Comment by dbu** [comment]
looks good!

can you please rebase, there seems to be a conflict now.

**Comment by Nyholm** [comment]
Sorry, 

I've now rebased the PR

**Comment by dbu** [comment]
thanks!

**Comment by Nyholm** [comment]
Thank you for merging

**Pull request merged**
